### ISSUE TITLE
评估模型时出错

### ISSUE THREAD

**Issue by adureychloe** [Qznan/SpanKL#7]
在运行train_clner.py时，当运行到测试过滤数据时，会抛出错误：

> Traceback (most recent call last):
  File "train_clner.py", line 1210, in <module>
    train_main(args)
  File "train_clner.py", line 981, in train_main
    spankl_ner(model, loader, args, learn_mode='cl')
  File "train_clner.py", line 795, in spankl_ner
    m = spankl_eval(model, test_tasks_dataloaders_Filter[task_id], task_id, loader, info_str='Test Filter', mode='so_far',
  File "train_clner.py", line 46, in spankl_eval
    for i, inputs_dct in enumerate(iterator):  # iter steps
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/workspace/code/SpanKL/data_reader.py", line 252, in span_batcher
    max_len = max(e['len'] for e in batch_e)
  File "/workspace/code/SpanKL/data_reader.py", line 252, in <genexpr>
    max_len = max(e['len'] for e in batch_e)
TypeError: 'NoneType' object is not subscriptable

异常出现在collate_fn中的batch_e是None。请问这个怎么解决呢？

**Comment by adureychloe** [comment]
抱歉，是我不小心把return多打了空格。。。
